steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/apache1', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/apache1']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ["run", "deploy", "mysvc", "--image", "gcr.io/${PROJECT_ID}/apache1", "--port", "80", "--platform", "managed", "--region","asia-southeast1","--allow-unauthenticated"]