steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/basic-tube-373302/apacheimage-develop', '.']

  - name: 'gcr.io/cloud-builders/docker'   
    args: ['push', 'gcr.io/basic-tube-373302/apacheimage-develop'] 

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'testimage', '--image','gcr.io/basic-tube-373302/apacheimage-develop','--port','80', '--region','asia-northeast1','--platform','managed', '--allow-unauthenticated' ]  

