steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/basic-tube-373302/apacheimage', '.']

  - name: 'gcr.io/cloud-builders/docker'   
    args: ['push', 'gcr.io/basic-tube-373302/apacheimage'] 

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'testimage', '--image','gcr.io/basic-tube-373302/apacheimage','port','80', '--region','global','--platform','managed', '--allow-unauthenticated' ]  

