steps:
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', 'gcr.io/basic-tube-373302/apacheimage-release', '.']

  # - name: 'gcr.io/cloud-builders/docker'   
  #   args: ['push', 'gcr.io/basic-tube-373302/apacheimage-release'] 

  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['run', 'deploy', 'shailendra-release', '--image','gcr.io/basic-tube-373302/apacheimage-release','--port','80', '--region','asia-northeast1','--platform','managed', '--allow-unauthenticated' ]  

  # - name: 'gcr.io/cloud-builders/git'
  #   args: ['checkout', 'develop']

  - name: 'gcr.io/cloud-builders/git'
    args: ['branch'] 

  # - name: 'gcr.io/cloud-builders/git'
  #   args: ['checkout','develop']

  # - name: 'gcr.io/cloud-builders/git'
  #   args: [ 'tag ','v0.1'] 

  # - name: 'gcr.io/cloud-builders/git'
  #   args: ['config','user.name',] 
   

  - name: 'gcr.io/cloud-builders/git'
    args: ['config','user.name','SVrma'] 

  - name: 'gcr.io/cloud-builders/git'
    args: ['config','user.password','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']   
  
  - name: 'gcr.io/cloud-builders/git'
    args: ['push','https://github.com/SVrma/cloudbuild-dockerImage.git']  
  
    
       
      #  git checkout develop
      #  git tag v1.0.1
      #  git push origin --tags
      