steps:
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', 'gcr.io/basic-tube-373302/apacheimage-release', '.']

  # - name: 'gcr.io/cloud-builders/docker'   
  #   args: ['push', 'gcr.io/basic-tube-373302/apacheimage-release'] 

  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['run', 'deploy', 'shailendra-release', '--image','gcr.io/basic-tube-373302/apacheimage-release','--port','80', '--region','asia-northeast1','--platform','managed', '--allow-unauthenticated' ]  

  # - name: 'gcr.io/cloud-builders/git'
  #   args: ['checkout', 'develop']

  - name: 'gcr.io/cloud-builders/git'
    args: ['branch'] 

  # - name: 'gcr.io/cloud-builders/git'
  #   args: ['checkout','develop']

  # - name: 'gcr.io/cloud-builders/git'
  #   args: [ 'tag ','v0.1'] 

  # - name: 'gcr.io/cloud-builders/git'
  #   args: ['config','user.name',] 
   

  - name: 'gcr.io/cloud-builders/git'
    args: ['config','user.name','SVrma'] 

  # - name: 'gcr.io/cloud-builders/git'
  #   args: ['config','user.password','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']   
  
  # - name: 'gcr.io/cloud-builders/git'
  #   args: ['push','https://github.com/SVrma/cloudbuild-dockerImage.git']  

  - name: gcr.io/cloud-builders/git
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      echo "Cloning repo ..."
      git checkout master
      git config --global user.name SVrma
      git config --global user.email mxx.verma@gmail.com
      git tag v1.0.1
      git push origin --tags
    
  
    
       
    